{
 "title": "WAP Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   { "name": "mongodbClusterName", "query": { "query": "WAP" } },
   {
    "name": "nodeName",
    "query": {
     "query": "WAP{mongodbClusterName=~\"$mongodbClusterName\"}"
    }
   }
  ]
 },
 "panels": [
  { "title": "Connection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active Connections",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "WAP{mongodbClusterName=~\"$mongodbClusterName\",attribute=\"us\",type=\"conn\"} ",
     "legendFormat": "{{nodeName}}"
    }
   ]
  },
  {
   "title": "Available connections",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "WAP{mongodbClusterName=~\"$mongodbClusterName\",attribute=\"avl\",type=\"conn\"} ",
     "legendFormat": "{{nodeName}}"
    }
   ]
  },
  {
   "title": "oplogWindow",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "targets": [
    {
     "expr": "WAP{mongodbClusterName=~\"$mongodbClusterName\",type=\"oplogWindow\"}",
     "legendFormat": "{{nodeName}}"
    }
   ]
  },
  {
   "title": "oplogSize",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "WAP{mongodbClusterName=~\"$mongodbClusterName\",type=\"oplogSize\"}",
     "legendFormat": "{{nodeName}}"
    }
   ]
  },
  {
   "title": "openCursor",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "WAP{mongodbClusterName=~\"$mongodbClusterName\",type=\"openCursor\"}",
     "legendFormat": "{{nodeName}}"
    }
   ]
  },
  {
   "title": "indexSize",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "WAP{mongodbClusterName=~\"$mongodbClusterName\",type=\"indexSize\"}",
     "legendFormat": "{{nodeName}}"
    }
   ]
  },
  { "title": "QPS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "QPS-cmd",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "WAP{mongodbClusterName=~\"$mongodbClusterName\",attribute=\"cmd\",type=\"qps\"}",
     "legendFormat": "{{mongodbClusterName}}:{{nodeName}}"
    }
   ]
  },
  {
   "title": "QPS-delete",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "expr": "WAP{mongodbClusterName=~\"$mongodbClusterName\",attribute=\"delete\",type=\"qps\"}",
     "legendFormat": "{{mongodbClusterName}}:{{nodeName}}"
    }
   ]
  },
  {
   "title": "QPS-update",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "WAP{mongodbClusterName=~\"$mongodbClusterName\",attribute=\"update\",type=\"qps\"}",
     "legendFormat": "{{mongodbClusterName}}:{{nodeName}}"
    }
   ]
  },
  {
   "title": "QPS-getMore",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "targets": [
    {
     "expr": "WAP{mongodbClusterName=~\"$mongodbClusterName\",attribute=\"getMore\",type=\"qps\"}",
     "legendFormat": "{{mongodbClusterName}}:{{nodeName}}"
    }
   ]
  },
  {
   "title": "QPS-query",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "WAP{mongodbClusterName=~\"$mongodbClusterName\",attribute=\"query\",type=\"qps\"}",
     "legendFormat": "{{mongodbClusterName}}:{{nodeName}}"
    }
   ]
  },
  {
   "title": "QPS-insert",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "targets": [
    {
     "expr": "WAP{mongodbClusterName=~\"$mongodbClusterName\",attribute=\"insert\",type=\"qps\"}",
     "legendFormat": "{{mongodbClusterName}}:{{nodeName}}"
    }
   ]
  },
  { "title": "mongodb详细信息", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "cacheFlow",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "WAP{mongodbClusterName=~\"$mongodbClusterName\",nodeName=~\"$nodeName\",type=\"cacheFlow\",attribute=\"brin\"}",
     "legendFormat": "{{nodeName}}_brin"
    },
    {
     "expr": "WAP{mongodbClusterName=~\"$mongodbClusterName\",nodeName=~\"$nodeName\",type=\"cacheFlow\",attribute=\"bwfr\"}",
     "legendFormat": "{{nodeName}}_bwfr"
    }
   ]
  },
  {
   "title": "latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 54 },
   "targets": [
    {
     "expr": "WAP{mongodbClusterName=~\"$mongodbClusterName\",nodeName=~\"$nodeName\",type=\"latency\",attribute=\"r\"}",
     "legendFormat": "{{nodeName}}_r"
    },
    {
     "expr": "WAP{mongodbClusterName=~\"$mongodbClusterName\",nodeName=~\"$nodeName\",type=\"latency\",attribute=\"w\"}",
     "legendFormat": "{{nodeName}}_w"
    }
   ]
  },
  {
   "title": "targetQ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 63 },
   "targets": [
    {
     "expr": "WAP{mongodbClusterName=~\"$mongodbClusterName\",nodeName=~\"$nodeName\",attribute=\"scanObject\",type=\"targetQ\"}",
     "legendFormat": "{{nodeName}}_scanObject"
    },
    {
     "expr": "WAP{mongodbClusterName=~\"$mongodbClusterName\",nodeName=~\"$nodeName\",attribute=\"scanned\",type=\"targetQ\"}",
     "legendFormat": "{{nodeName}}_scanned"
    }
   ]
  },
  {
   "title": "memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 63 },
   "targets": [
    {
     "expr": "WAP{mongodbClusterName=~\"$mongodbClusterName\",nodeName=~\"$nodeName\",attribute=\"virtual\",type=\"memory\"}",
     "legendFormat": "{{nodeName}}_virtual"
    },
    {
     "expr": "WAP{mongodbClusterName=~\"$mongodbClusterName\",nodeName=~\"$nodeName\",attribute=\"resident\",type=\"memory\"}",
     "legendFormat": "{{nodeName}}_resident"
    }
   ]
  },
  {
   "title": "net",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "WAP{mongodbClusterName=~\"$mongodbClusterName\",nodeName=~\"$nodeName\",attribute=\"in\",type=\"net\"}",
     "legendFormat": "{{nodeName}}_in"
    },
    {
     "expr": "WAP{mongodbClusterName=~\"$mongodbClusterName\",nodeName=~\"$nodeName\",attribute=\"out\",type=\"net\"}",
     "legendFormat": "{{nodeName}}_out"
    },
    {
     "expr": "WAP{mongodbClusterName=~\"$mongodbClusterName\",nodeName=~\"$nodeName\",attribute=\"cmpOut\",type=\"net\"}",
     "legendFormat": "{{nodeName}}_cmpOut"
    },
    {
     "expr": "WAP{mongodbClusterName=~\"$mongodbClusterName\",nodeName=~\"$nodeName\",attribute=\"cmpIn\",type=\"net\"}",
     "legendFormat": "{{nodeName}}_cmpIn"
    }
   ]
  },
  {
   "title": "cacheUsage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "WAP{mongodbClusterName=~\"$mongodbClusterName\",nodeName=~\"$nodeName\",attribute=\"bdirty\",type=\"cacheUsage\"}",
     "legendFormat": "{{nodeName}}_bdirty"
    },
    {
     "expr": "WAP{mongodbClusterName=~\"$mongodbClusterName\",nodeName=~\"$nodeName\",attribute=\"bused\",type=\"cacheUsage\"}",
     "legendFormat": "{{nodeName}}_bused"
    }
   ]
  },
  {
   "title": "databaseLock",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 81 },
   "targets": [
    {
     "expr": "WAP{mongodbClusterName=~\"$mongodbClusterName\",nodeName=~\"$nodeName\",type=\"databaseLock\",attribute=\"r\"}",
     "legendFormat": "{{nodeName}}_r"
    },
    {
     "expr": "WAP{mongodbClusterName=~\"$mongodbClusterName\",nodeName=~\"$nodeName\",type=\"databaseLock\",attribute=\"r_i\"}",
     "legendFormat": "{{nodeName}}_ri"
    },
    {
     "expr": "WAP{mongodbClusterName=~\"$mongodbClusterName\",nodeName=~\"$nodeName\",type=\"databaseLock\",attribute=\"w\"}",
     "legendFormat": "{{nodeName}}_w"
    },
    {
     "expr": "WAP{mongodbClusterName=~\"$mongodbClusterName\",nodeName=~\"$nodeName\",type=\"databaseLock\",attribute=\"w_i\"}",
     "legendFormat": "{{nodeName}}_w_i"
    }
   ]
  }
 ]
}